import { SocketProvider } from "~/context/SocketProvider";
import "./globals.css";
import Providers from "./providers";
import Header from "~/components/common/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-hidden">
      <body className="h-full max-h-screen overflow-hidden bg-zinc-950 text-white flex flex-col">
        <Providers>
          <SocketProvider>
            <Header />
            {children}
          </SocketProvider>
        </Providers>
      </body>
    </html>
  );
}
